name: oson_market
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  http: ^1.2.1
  provider: ^6.1.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  adaptive_theme: ^3.6.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.9
  flutter_facebook_auth: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf

